EventBillApplication/Controllers/EventEntryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EventBillApplication.DAL;
using EventBillApplication.Models;
using System.Globalization;
namespace EventBillApplication.Controllers
{
    public class EventEntryController : SuperController
    {
        //
        // GET: /EventEntry/
        cl_EventEntry obj = new cl_EventEntry();
        public ActionResult Index()
        {
            var curuser = Helper.Helper.CurrentLoggedUser.Id;
            var list = obj.Get(curuser);
            return View(list);
        }

        public ActionResult CreditstatementReport(int? id,int userid)
        {
            //var records = obj.Getcreditstatement(id, userid);
            var records = obj.getcreditdetail(id,userid);
            return View(records);
        }

        public ActionResult InsertCreditAmountentry(long id)
        {

            ViewBag.evententryid = id;
            var curuuserid=Helper.Helper.CurrentLoggedUser.Id;
            var listofuserid = obj.Getbyid((int)id);
            List<UserEntity> eventuserlist = new List<UserEntity>();
            foreach (var cust in listofuserid.customerlist)
            {
                eventuserlist.Add(cust.UserMaster);
            }
            
          //  var userlist = new cl_User().Get().Where(x=>x.Id!=curuuserid).ToList();
            eventuserlist = eventuserlist.Where(x => x.Id != curuuserid).ToList();




            ViewBag.userlist = new SelectList(eventuserlist, "Id", "Fullname", 0);
            return View();
        }

        [HttpPost]
        public ActionResult InsertCreditAmountentry(FormCollection frm)
        {
            var currentuserid = Helper.Helper.CurrentLoggedUser.Id;
            long evenentryid = Convert.ToInt64(frm["eventryid"]);
            List<CreditAmountEntity> creditlist = new List<CreditAmountEntity>();
            var customerlist = frm["rowstr"].ToString();
            if (customerlist != null)
            {
                string[] custstr = customerlist.Split('#');

                foreach (var cust in custstr)
                {
                    CreditAmountEntity entity = new CreditAmountEntity();
                    var custarr = cust.Split('~');
                   // EventCustomerentity eventcustentity = new EventCustomerentity();
                    entity.Creditedfrom =Convert.ToInt32(custarr[0]);
                    entity.Creditamount = Convert.ToDecimal(custarr[1]);
                    entity.Creditedto = currentuserid;
                    entity.evententryid = evenentryid;
                    entity.IsActive = true;
                    creditlist.Add(entity);

                }
            }

            var inserted = obj.Insertcreditamountentry(creditlist);
            if (inserted)
                return RedirectToAction("Index");

            return View();
        }


        public ActionResult Create()
        {

            var userlist = new cl_User().Get();
            var eventlist = new cl_Event().Get();
            ViewBag.eventlist = new SelectList(eventlist, "Id", "Eventname", 0);
            ViewBag.userlist = new SelectList(userlist, "Id", "Fullname", 0);
            return View();
        }


        [HttpPost]
        public ActionResult Create(FormCollection frm)
        {

            EventEntryEntity entity = new EventEntryEntity();


            entity.Createddate = DateTime.Now;
            entity.Createdby = Helper.Helper.CurrentLoggedUser.Id;
            entity.Eventid=Convert.ToInt64(frm["eventid"]);
            entity.Location=frm["Location"].ToString();
            entity.TotalAmount =Convert.ToDecimal(frm["TotalAmount"]);
            entity.IsActive=true;

            string eventdatestr = frm["entrydate"].ToString();

            if (eventdatestr != "")
            {
                DateTime evdate = DateTime.ParseExact(eventdatestr, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                entity.Eventdate = evdate;


            }
            List<EventCustomerentity> eventcustlist = new List<EventCustomerentity>();
            var customerlist = frm["rowstr"].ToString();
            if (customerlist != null)
            {
                string[] custstr = customerlist.Split('#');

                foreach (var cust in custstr)
                {
                    var custarr = cust.Split('~');
                    EventCustomerentity eventcustentity = new EventCustomerentity();
                    eventcustentity.Eventcustomerid = Convert.ToInt32(custarr[0]);
                    eventcustentity.Paidamount = Convert.ToDecimal(custarr[1]);
                    eventcustlist.Add(eventcustentity);

                }
            }

            entity.customerlist = eventcustlist;
            var inserted = obj.Insert(entity);
            if (inserted)
            {
                return RedirectToAction("Index");
            }


           return View();
        }


        public ActionResult Edit(int id)
        {

            var record = obj.Getbyid(id);
            var userlist = new cl_User().Get();
            var eventlist = new cl_Event().Get();
            ViewBag.eventlist = new SelectList(eventlist, "Id", "Eventname", record.Eventid);
            ViewBag.userlist = new SelectList(userlist, "Id", "Fullname", 0);
            return View(record);
        }



        public JsonResult Delete(long id)
        {

            var result = obj.Delete(id);
            return Json(result);
        }


    }
}

EventBillApplication/Views/EventEntry/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEvent.cshtml";
}

<link type="text/css" rel="stylesheet" href="~/Content/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css" />
<link type="text/css" rel="stylesheet" href="~/Content/vendors/datepicker/css/bootstrap-datepicker.min.css" />
<link type="text/css" rel="stylesheet" href="~/Content/vendors/bootstrap-timepicker/css/bootstrap-timepicker.min.css" />
<header class="head">
    <div class="main-bar row">
        <div class="col-sm-5 col-lg-6 skin_txt">
            <h4 class="nav_top_align">
                <i class="fa fa-pencil"></i>
                New Event Entry
            </h4>
        </div>
        <div class="col-sm-7 col-lg-6">
            <ol class="breadcrumb float-xs-right nav_breadcrumb_top_align">
                <li class="breadcrumb-item">
                    <a href="index.html">
                        <i class="fa fa-home" data-pack="default" data-tags=""></i> Dashboard
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">User</a>
                </li>
                <li class="active breadcrumb-item"> New Event Entry</li>
            </ol>
        </div>
    </div>
</header>

<div class="outer">
    <div class="inner bg-container forms">
        <div class="row">

            <div class="col-xl-12">
                <div class="card m-t-10">
                    <div class="card-header bg-white">
                        Event Entry
                    </div>
                    <div class="card-block">
                       @using (Html.BeginForm("Create", "EventEntry", null, FormMethod.Post, new { @class = "form-horizontal form-simple" }))
                       {
                        @Html.AntiForgeryToken()
                            <fieldset>



                                <div class="form-group row m-t-35">
                                     <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Entry date *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                      <div class="input-group">
                                     <input type="text" class="form-control" placeholder="dd/mm/yyyy" data-date-format="dd/mm/yyyy" id="entrydate" name="entrydate">
                                      <span class="input-group-addon add-on">
                                       <i class="fa fa-calendar"></i>
                                      </span>
                                      </div>
                                   
                                     </div>
                                 </div>

                                <div class="form-group row m-t-35">
                                    <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Event *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                        <div class="input-group">


                                             @Html.DropDownList("eventid", (IEnumerable<SelectListItem>)ViewBag.eventlist,"Select",new { @class = "form-control chzn-select", @data_placeholder = "Select" })
                                            @Html.ValidationMessage("eventid", new { @class = "text-danger" })
                                               <span id="eventidmsg" class="text-danger"></span>
                                         </div>
                                    </div>
                                 
                                </div>

                                <div class="form-group row m-t-35">
                                     <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Customer *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                        <div class="input-group">


                                             @Html.DropDownList("Userid", (IEnumerable<SelectListItem>)ViewBag.userlist,"Select", new { @class = "form-control chzn-select", @data_placeholder = "Select" })
                                            @Html.ValidationMessage("Userid", new { @class = "text-danger" })
                                            <span id="useridmsg" class="text-danger"></span>
                                         </div>
                                    </div>

                                     <div class="col-lg-3 col-xl-2 text-lg-right">
                                      <button type="button" class="btn btn-primary" onclick="addEventuser()">Add</button>
                                    </div>


                                 </div>

                                  <div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Event Customer *</label>
                                    </div>
                                      <div class="col-lg-8 col-xl-4">
                                    <table class="table table-striped table-bordered table-advance table-hover" id="usertable">
                                        <tr class="titlerow">
                                           @* <th>Sr No</th>*@
                                            <th>Name</th>
                                             <th>Amount</th>
                                            <th></th>
                                        </tr>
                                        <tbody>


                                        </tbody>

                                    </table>
                                          </div>
                                
                                 </div>





                               <div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Location *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                        <div class="input-group">


                                            @Html.TextBox("Location", "", new { @class = "form-control", @placeholder = "" })
                                            @Html.ValidationMessage("Location", new { @class = "text-danger" })
                                         </div>
                                    </div>
                                
                                        </div>

                                 <div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Total Amount</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                        <div class="input-group">

                                           
                                          @Html.TextBox("TotalAmount","", new { @class = "form-control", @placeholder = "" })
                                            @Html.ValidationMessage("TotalAmount", new { @class = "text-danger" })
                                             <span id="TotalAmountmsg" class="text-danger"></span>
                                         </div>
                                    </div>
                                
                                     </div>

                                  @*<div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Remark </label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                        <div class="input-group">


                                            @Html.TextBox("Remark", "", new { @class = "form-control", @placeholder = "" })
                                            @Html.ValidationMessage("Remark", new { @class = "text-danger" })
                                         </div>
                                    </div>
                                
                                        </div>*@

                                    <div class="form-group row">
                                        <div class="col-lg-9 push-xl-2 push-lg-3">

                                            <input type="submit" class="btn btn-primary layout_btn_prevent" onclick="return isvalidate()" value="Save" />
                                            <input type="button" class="btn btn-warning layout_btn_prevent" onclick="location.href='@Url.Action("Index", "User")'" value="Cancel" />

                                        </div>
                                    </div>
                                <input type="hidden" name="rowstr" id="rowstr"/>
                </fieldset>
                       }
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Content/vendors/datepicker/js/bootstrap-datepicker.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/vendors/datetimepicker/js/DateTimePicker.min.js")"></script>
<script>
    $('#entrydate').datepicker({
        todayHighlight: true,
        autoclose: true
    });

    function validitem()
    {
        var valid = true;

        var userid = $("#Userid").val();
       


        $('#usertable tr').each(function () {

            if ($(this).find('.validitemcatrow').val() == userid) {
                valid=false;
            }
        });

        return valid;
    }

    function addEventuser()
    {
        var user = document.getElementById("Userid");
        var selecteduser=user.options[user.selectedIndex].text;
        var selecteduserid=$("#Userid").val();;
        
        var uservalid=validitem();
        if(uservalid)
        {
            $('#useridmsg').html("");
            var div="<tr><td> "+selecteduser+"<input type='hidden' value='"+selecteduserid+"' class='row validitemcatrow'/></td><<td><input type=text class='form-control row amountrow'/></td><td><button type='button' id='btnDelete' class='deleterow btn btn btn-danger btn-xs'>Remove</button></td></tr>";
            $('#usertable').append(div);
        }
        else{
            $('#useridmsg').html("selected user already added");
        }

    }

    $(document).on("click", ".deleterow", function () {
     
        $(this).closest("tr").remove(); // 
      
       

    });
    function userpaidamt()
    {
        var totalamt=0;
        $(this).find('.amountrow').each(function (i) {
            var amt;
            if($(this).val()=="")
                amt=0;
            else
                amt=$(this).val();

            totalamt=totalamt+parseFloat(amt);
        });
        return totalamt;
    }

    function isvalidate()
    {

        var isvalid=true;

        var userid=$('#Userid').val();
        var event=$('#eventid').val();
        var totalamt=$('#TotalAmount').val();

        //if(userid=="")
        //{
        //    $('#useridmsg').html("select user");
        //}
        //else{
        //    $('#useridmsg').html("");
        //}
        if(event=="")
        {
            isvalid=false;
            $('#eventidmsg').html("select event");
        }
        else{
            $('#eventidmsg').html("");

        }
        if(totalamt=="" || totalamt=="0")
        {
            isvalid=false;
            $('#TotalAmountmsg').html("Enter valid amount");
        }
        else{
            $('#TotalAmountmsg').html("");
            //var totalpaid=userpaidamt();
            //if(parseFloat(totalamt)!=parseFloat(totalpaid))
            //{
            //    isvalid=false;
            //    $('#TotalAmountmsg').html("the sum of all customer paidamount is not equal to Total amount");
            //}
            //else{
            //    $('#TotalAmountmsg').html("");
            //}

        }



        // var rawitemstr = "";
        if(isvalid==true)
        {
            var str="";
            var $dataRows = $("#usertable tr:not('.titlerow')");
            var rowlenght = $dataRows.length;
            var rowcount = 0;
            $dataRows.each(function () {
                count = 0;
                rowcount++;
                $(this).find('.row').each(function (i) {
                    var itemlist = ($(this).val());  //here get td value
                    count++;

                    if (itemlist != undefined) {

                        if (count == 2) {
                            str += itemlist;
                        }
                        else {
                            str += itemlist + "~";
                        }
                    }

                });

                if (rowcount == rowlenght) {

                }
                else {
                    str += "#";
                }

            });

            //alert(str);
            $('#rowstr').val(str);
        }




        return isvalid;
    }


</script>

EventBillApplication/Views/EventEntry/CreditstatementReport.cshtml
@model List<EventBillApplication.Models.CreditStatemententity>

@{
    ViewBag.Title = "CreditstatementReport";
    Layout = "~/Views/Shared/_LayoutEvent.cshtml";
}


<header class="head">
    <div class="main-bar row">
        <div class="col-lg-6 col-md-4 col-sm-4">
            <h4 class="nav_top_align">
                <i class="fa fa-th"></i>
                Credit Statement detail
            </h4>
        </div>
        <div class="col-lg-6 col-md-8 col-sm-8">
            <ol class="breadcrumb float-xs-right nav_breadcrumb_top_align">
                <li class="breadcrumb-item">
                    <a href="index.html">
                        <i class="fa fa-home" data-pack="default" data-tags=""></i>
                        Dashboard
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#"></a>
                </li>
                <li class="breadcrumb-item active">  Credit Statement detail</li>
            </ol>
        </div>
    </div>
</header>

<div class="outer">
    <div class="inner bg-light lter bg-container">
        <div class="row">
            <div class="col-xs-12 data_tables">
                <!-- BEGIN EXAMPLE1 TABLE PORTLET-->
                <div class="card">
                    <div class="card-header bg-white">
                        <i class="fa fa-table"></i>  Credit Statement detail
                    </div>
                    <div class="card-block p-t-25">
                        <button id="del_button" class="btn btn-primary" onclick="location.href='@Url.Action("Index", "EventEntry")'">back</button>
                        <div class="">
                            <div class="pull-sm-right">
                                <div class="tools pull-sm-right"></div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover" id="sample_1">
                            <thead>
                                <tr>
                                   
                                    <th>Credited From</th>
                                    <th>Credit Amount</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                               @foreach (var item in Model)
                                {
                                    <tr>
                                        
                                        <td>@item.creditby</td>
                                         <td>@item.creditamount</td>
                                       
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

EventBillApplication/Views/EventEntry/Index.cshtml
@model List<EventBillApplication.Models.EventEntryEntity>
@using EventBillApplication.Helper
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutEvent.cshtml";
}

<header class="head">
    <div class="main-bar row">
        <div class="col-lg-6 col-md-4 col-sm-4">
            <h4 class="nav_top_align">
                <i class="fa fa-th"></i>
                Event Entry detail
            </h4>
        </div>
        <div class="col-lg-6 col-md-8 col-sm-8">
            <ol class="breadcrumb float-xs-right nav_breadcrumb_top_align">
                <li class="breadcrumb-item">
                    <a href="index.html">
                        <i class="fa fa-home" data-pack="default" data-tags=""></i>
                        Dashboard
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#"></a>
                </li>
                <li class="breadcrumb-item active">  Event Entry detail</li>
            </ol>
        </div>
    </div>
</header>

<div class="outer">
    <div class="inner bg-light lter bg-container">
        <div class="row">
            <div class="col-xs-12 data_tables">
                <!-- BEGIN EXAMPLE1 TABLE PORTLET-->
                <div class="card">
                    <div class="card-header bg-white">
                        <i class="fa fa-table"></i> Event Entry Details
                    </div>
                    <div class="card-block p-t-25">
                        <button id="del_button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "EventEntry")'"> Add EventEntry</button>
                        <div class="">
                            <div class="pull-sm-right">
                                <div class="tools pull-sm-right"></div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover" id="sample_1">
                            <thead>
                                <tr>
                                     <th>Event name</th>
                                    <th>Event date</th>
                                    <th>Event Amount</th>
                                    <th>Action</th>
                                    <th>Credit Statement</th>
                                    <th>Credit Entry</th>
                                </tr>
                            </thead>
                            <tbody>
                               @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.EventMaster.Eventname</td>
                                        <td>@item.Eventdate</td>
                                         <td>@item.TotalAmount</td>
                                        <td>
                                            <a class="edit" data-toggle="tooltip" data-placement="top" title="" href="@Url.Action("Edit", "EventEntry", new {id=item.Id })" data-original-title="Edit"><i class="fa fa-pencil text-warning"></i></a>&nbsp; &nbsp;
                                            <a class="delete hidden-xs hidden-sm" data-toggle="tooltip" data-placement="top" title="" id="@item.Id" href="#" data-original-title="Delete" onclick="delete_(this.id)">
                                                <i class="fa fa-trash text-danger">
                                                </i>
                                            </a>

                                        </td>
                                        <td>
                                   <button id="del_button" class="btn btn-primary" onclick="location.href='@Url.Action("CreditstatementReport", "EventEntry", new {id=@item.Id,userid=@Helper.CurrentLoggedUser.Id })'">View Credit details</button>
                                        </td>
                                        <td>
                                   <button id="del_button" class="btn btn-primary" onclick="location.href='@Url.Action("InsertCreditAmountentry", "EventEntry", new {id=@item.Id })'">Credit Amount Entry</button>
                                        </td>
                                    </tr>
                                   
                                }
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Content/js/pages/datatable.js"></script>
<script type="text/javascript" src="@Url.Content("~/Content/js/pages/sweet_alerts.js")"></script>
<script>

    function delete_(id)
    {

        var _id = id;
        var param = { 'id': _id };

            swal({
                title: 'Are you sure?',
                text: 'You won\'t be able to revert this!',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#00c0ef',
                cancelButtonColor: '#ff8080',
                confirmButtonText: 'Yes, delete it!'
            }).then(function () {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "EventEntry")',
                    data: JSON.stringify(param),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {

                        if (result == true) {
                           

                            window.location.reload();
                        }

                    },
                    failure: function (response) {
                        alert(response.d);
                    }
                });
            });
            return false;
    }


    var initTable1 = function () {
        var table = $('#sample_1');
        
        table.DataTable({
            dom: 'Bflr<"table-responsive"t>ip',
            buttons: [
                'copy', 'csv', 'print'
            ]
        });
        var tableWrapper = $('#sample_1_wrapper'); // datatable creates the table wrapper by adding with id {your_table_id}_wrapper
        tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown
    }
</script>