EventBillApplication/Controllers/BillSettlementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EventBillApplication.DAL;
using EventBillApplication.Models;
using EventBillApplication.Helper;
using System.Globalization;

namespace EventBillApplication.Controllers
{
    public class BillSettlementController : SuperController
    {
        //
        // GET: /BillSettlement/
        cl_Billsettlement obj = new cl_Billsettlement();

        public JsonResult getBalance(int creditbyid)
        {
            var currentuser=Helper.Helper.CurrentLoggedUser.Id;
            var balance = obj.getbalance(currentuser, creditbyid);
            return Json(balance);

        }

        public ActionResult Index()
        {
            var list = obj.Get().Where(x => x.Paidby == Helper.Helper.CurrentLoggedUser.Id).ToList();

            return View(list);
        }
        public ActionResult Create()
        {
            var currentuser = Helper.Helper.CurrentLoggedUser.Id;
            var userlist = new cl_User().Get().Where(x=>x.Id!=currentuser).ToList();
            ViewBag.userlist = new SelectList(userlist, "Id", "Fullname", 0);
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection frm,Billsettlemententity entity)
        {
            string eventdatestr = frm["entrydate"].ToString();
            entity.Paidby = Helper.Helper.CurrentLoggedUser.Id;
            if (eventdatestr != "")
            {
                DateTime evdate = DateTime.ParseExact(eventdatestr, "dd/MM/yyyy", CultureInfo.InvariantCulture);

                entity.Entrydate = evdate;
             }
            var inserted = obj.Insert(entity);
            if (inserted)
                return RedirectToAction("Index");
            return View();
        }



    }
}

EventBillApplication/Views/BillSettlement/Create.cshtml
@model EventBillApplication.Models.Billsettlemententity
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutEvent.cshtml";
}

@*<h2>Create Bill settlement</h2>*@
<link type="text/css" rel="stylesheet" href="~/Content/vendors/jasny-bootstrap/css/jasny-bootstrap.min.css" />
<link type="text/css" rel="stylesheet" href="~/Content/vendors/datepicker/css/bootstrap-datepicker.min.css" />
<link type="text/css" rel="stylesheet" href="~/Content/vendors/bootstrap-timepicker/css/bootstrap-timepicker.min.css" />
<header class="head">
    <div class="main-bar row">
        <div class="col-sm-5 col-lg-6 skin_txt">
            <h4 class="nav_top_align">
                <i class="fa fa-pencil"></i>
                New Bill settlement Entry
            </h4>
        </div>
        <div class="col-sm-7 col-lg-6">
            <ol class="breadcrumb float-xs-right nav_breadcrumb_top_align">
                <li class="breadcrumb-item">
                    <a href="index.html">
                        <i class="fa fa-home" data-pack="default" data-tags=""></i> Dashboard
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Bill settlement</a>
                </li>
                <li class="active breadcrumb-item"> New Bill settlement Entry</li>
            </ol>
        </div>
    </div>
</header>

<div class="outer">
    <div class="inner bg-container forms">
        <div class="row">

            <div class="col-xl-12">
                <div class="card m-t-10">
                    <div class="card-header bg-white">
                        New Bill settlement Entry
                    </div>
                    <div class="card-block">
                       @using (Html.BeginForm("Create", "BillSettlement", null, FormMethod.Post, new { @class = "form-horizontal form-simple" }))
                       {
                        @Html.AntiForgeryToken()
                            <fieldset>

                               <div class="form-group row m-t-35">
                                     <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Entry date *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                      <div class="input-group">
                                     <input type="text" class="form-control" placeholder="dd/mm/yyyy" data-date-format="dd/mm/yyyy" id="entrydate" name="entrydate">
                                      <span class="input-group-addon add-on">
                                       <i class="fa fa-calendar"></i>
                                      </span>
                                      </div>
                                   
                                     </div>
                                 </div>

                                <div class="form-group row m-t-35">
                                    <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Select  </label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                       


                                             @Html.DropDownList("Creditedfrom", (IEnumerable<SelectListItem>)ViewBag.userlist,"Select", new { @class = "form-control chzn-select", @data_placeholder = "Select",@onchange="getcreditamt()"})
                                            @Html.ValidationMessage("Creditedfrom", new { @class = "text-danger" })
                                            <span id="useridmsg" class="text-danger"></span>
                                         
                                    </div>
                                  
                                </div>

                                <div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label"> Credit Balance *</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                       


                                            @Html.TextBox("Creditamount", "", new { @class = "form-control", @placeholder = "" })
                                            @Html.ValidationMessage("Creditamount", new { @class = "text-danger" })
                                         
                                    </div>
                                
                                    </div>

                                 <div class="form-group row m-t-35">
                                       <div class="col-lg-3 col-xl-2 text-lg-right">
                                        <label for="name4" class=" form-control-label">Paid Amount</label>
                                    </div>
                                    <div class="col-lg-8 col-xl-4">
                                      

                                           
                                          @Html.TextBox("Paidamount","", new { @class = "form-control", @placeholder = "" })
                                            @Html.ValidationMessage("Paidamount", new { @class = "text-danger" })
                                             <span id="PaidAmountmsg" class="text-danger"></span>
                                        
                                    </div>
                                
                                     </div>

                                  

                                    <div class="form-group row">
                                        <div class="col-lg-9 push-xl-2 push-lg-3">

                                            <input type="submit" class="btn btn-primary layout_btn_prevent" onclick="return isvalidate()" value="Save" />
                                            <input type="button" class="btn btn-warning layout_btn_prevent" onclick="location.href='@Url.Action("Index", "User")'" value="Cancel" />

                                        </div>
                                    </div>

                                
                </fieldset>
                       }
                    </div>
                   
                </div>
            </div>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script type="text/javascript" src="@Url.Content("~/Content/vendors/datepicker/js/bootstrap-datepicker.min.js")"></script>
<script type="text/javascript" src="@Url.Content("~/Content/vendors/datetimepicker/js/DateTimePicker.min.js")"></script>
<script>
    $('#entrydate').datepicker({
        todayHighlight: true,
        autoclose: true
    });

    function isvalidate()
    {
        var valid=true;

        var balance=$('#Creditamount').val();
        if(parseInt(balance)<=0)
        {
            alert("Balance must be greater than 0");
            valid=false;
        }


        return valid;

    }


    function getcreditamt()
    {
        var credituserid=$('#Creditedfrom').val();
        var param={'creditbyid':credituserid};
        $.ajax({
            type: "POST",
            url: '@Url.Action("getBalance", "BillSettlement")',
                data: JSON.stringify(param),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result) {
            
                    $('#Creditamount').val(result);
                },
                failure: function (response) {
                    alert(response.d);
                }
        });


    }

  </script>

EventBillApplication/Views/BillSettlement/Index.cshtml
@model List<EventBillApplication.Models.Billsettlemententity>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutEvent.cshtml";
}
<link type="text/css" rel="stylesheet" href="~/Content/css/pages/sweet_alert.css">
<header class="head">
    <div class="main-bar row">
        <div class="col-lg-6 col-md-4 col-sm-4">
            <h4 class="nav_top_align">
                <i class="fa fa-th"></i>
                Bill Settlement Entry List
            </h4>
        </div>
        <div class="col-lg-6 col-md-8 col-sm-8">
            <ol class="breadcrumb float-xs-right nav_breadcrumb_top_align">
                <li class="breadcrumb-item">
                    <a href="index.html">
                        <i class="fa fa-home" data-pack="default" data-tags=""></i>
                        Dashboard
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#"></a>
                </li>
                <li class="breadcrumb-item active">  Bill Settlement Entry List</li>
            </ol>
        </div>
    </div>
</header>
<div class="outer">
    <div class="inner bg-light lter bg-container">
        <div class="row">
            <div class="col-xs-12 data_tables">
                <!-- BEGIN EXAMPLE1 TABLE PORTLET-->
                <div class="card">
                    <div class="card-header bg-white">
                        <i class="fa fa-table"></i>  Bill Settlement Entry Details
                    </div>
                    <div class="card-block p-t-25">
                        <button id="del_button" class="btn btn-primary" onclick="location.href='@Url.Action("Create", "BillSettlement")'"> Add BillSettlement</button>
                        <div class="">
                            <div class="pull-sm-right">
                                <div class="tools pull-sm-right"></div>
                            </div>
                        </div>
                        <table class="table table-striped table-bordered table-hover" id="sample_1">
                            <thead>
                                <tr>
                                    <th>Entry date</th>
                                     <th>Paid Amount</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Entrydate</td>
                                       <td>@item.Paidamount</td>
                                        <td>
                                           
                                            <a class="delete hidden-xs hidden-sm" data-toggle="tooltip" data-placement="top" title="" id="@item.Id" href="#" data-original-title="Delete" onclick="delete_(this.id)">
                                                <i class="fa fa-trash text-danger">
                                                </i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.8.2.min.js"></script>
<script src="~/Content/js/pages/datatable.js"></script>
<script type="text/javascript" src="@Url.Content("~/Content/js/pages/sweet_alerts.js")"></script>
<script>

    function delete_(id)
    {

        var _id = id;
        var param = { 'id': _id };

            swal({
                title: 'Are you sure?',
                text: 'You won\'t be able to revert this!',
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#00c0ef',
                cancelButtonColor: '#ff8080',
                confirmButtonText: 'Yes, delete it!'
            }).then(function () {

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "BillSettlement")',
                    data: JSON.stringify(param),
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {

                        if (result == true) {
                           

                            window.location.reload();
                        }

                    },
                    failure: function (response) {
                        alert(response.d);
                    }
                });
            });
            return false;
    }


    var initTable1 = function () {
        var table = $('#sample_1');
       
        table.DataTable({
            dom: 'Bflr<"table-responsive"t>ip',
            buttons: [
                'copy', 'csv', 'print'
            ]
        });
        var tableWrapper = $('#sample_1_wrapper'); // datatable creates the table wrapper by adding with id {your_table_id}_wrapper
        tableWrapper.find('.dataTables_length select').select2(); // initialize select2 dropdown
    }
</script>